@url=http://localhost:3000
@auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZjVmMTJlNC00NzA4LTQzMjAtOTYxMS0zODM4NjJhYmUyN2QiLCJlbWFpbCI6Im1pY2hhZWxAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6Ik1pY2hhZWwiLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNzU0ODA5MzYyLCJleHAiOjE3NTQ4MDkzNjh9.WqC0Qk1x4xv469ojxi_FQDFIh1625CcXnYN5UnZMn-k

###Create users
POST {{url}}/users/register
Content-Type: application/json

{
  "username": "Michael",
  "email": "michael@example.com",
  "password": "securePassword123"
}

###Update a user
GET {{url}}/users
Authorization: Bearer {{auth}}


###Sign in user
POST {{url}}/auths/signin
Content-Type: application/json

{
  "username": "Michael",
  "password": "securePassword123"
}